In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df = pd.read_csv("/content/car data.csv")
df

Car_Name        company  Year  Selling_Price  Present_Price  Kms_Driven  \
0       ritz  maruti suzuki  2014           3.35           5.59       27000   
1        sx4  maruti suzuki  2013           4.75           9.54       43000   
2       ciaz  maruti suzuki  2017           7.25           9.85        6900   
3    wagon r  maruti suzuki  2011           2.85           4.15        5200   
4      swift  maruti suzuki  2014           4.60           6.87       42450   
..       ...            ...   ...            ...            ...         ...   
296     city          honda  2016           9.50          11.60       33988   
297     brio          honda  2015           4.00           5.90       60000   
298     city          honda  2009           3.35          11.00       87934   
299     city          honda  2017          11.50          12.50        9000   
300     brio          honda  2016           5.30           5.90        5464   

    Fuel_Type Seller_Type Transmission  Owner  
0      Petrol      Dealer       Manual      0  
1      Diesel      Dealer       Manual      0  
2      Petrol      Dealer       Manual      0  
3      Petrol      Dealer       Manual      0  
4      Diesel      Dealer       Manual      0  
..        ...         ...          ...    ...  
296    Diesel      Dealer       Manual      0  
297    Petrol      Dealer       Manual      0  
298    Petrol      Dealer       Manual      0  
299    Diesel      Dealer       Manual      0  
300    Petrol      Dealer       Manual      0  

[301 rows x 10 columns]

In [ ]:
df.isnull().any()

Car_Name         False
company          False
Year             False
Selling_Price    False
Present_Price    False
Kms_Driven       False
Fuel_Type        False
Seller_Type      False
Transmission     False
Owner            False
dtype: bool

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   company        301 non-null    object 
 2   Year           301 non-null    int64  
 3   Selling_Price  301 non-null    float64
 4   Present_Price  301 non-null    float64
 5   Kms_Driven     301 non-null    int64  
 6   Fuel_Type      301 non-null    object 
 7   Seller_Type    301 non-null    object 
 8   Transmission   301 non-null    object 
 9   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(5)
memory usage: 23.6+ KB


In [ ]:
df['Year'].unique()

array([2014, 2013, 2017, 2011, 2018, 2015, 2016, 2009, 2010, 2012, 2003,
       2008, 2006, 2005, 2004, 2007])

In [ ]:
df['Owner'].unique()

array([0, 1, 3])

In [ ]:
df.describe()

Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [ ]:
df1 = df.copy()

In [ ]:
df1 = df1.drop("Owner",axis = 1)
df1

Car_Name        company  Year  Selling_Price  Present_Price  Kms_Driven  \
0       ritz  maruti suzuki  2014           3.35           5.59       27000   
1        sx4  maruti suzuki  2013           4.75           9.54       43000   
2       ciaz  maruti suzuki  2017           7.25           9.85        6900   
3    wagon r  maruti suzuki  2011           2.85           4.15        5200   
4      swift  maruti suzuki  2014           4.60           6.87       42450   
..       ...            ...   ...            ...            ...         ...   
296     city          honda  2016           9.50          11.60       33988   
297     brio          honda  2015           4.00           5.90       60000   
298     city          honda  2009           3.35          11.00       87934   
299     city          honda  2017          11.50          12.50        9000   
300     brio          honda  2016           5.30           5.90        5464   

    Fuel_Type Seller_Type Transmission  
0      Petrol      Dealer       Manual  
1      Diesel      Dealer       Manual  
2      Petrol      Dealer       Manual  
3      Petrol      Dealer       Manual  
4      Diesel      Dealer       Manual  
..        ...         ...          ...  
296    Diesel      Dealer       Manual  
297    Petrol      Dealer       Manual  
298    Petrol      Dealer       Manual  
299    Diesel      Dealer       Manual  
300    Petrol      Dealer       Manual  

[301 rows x 9 columns]

In [ ]:
df1 = df1.drop("Seller_Type",axis = 1)
df1

Car_Name        company  Year  Selling_Price  Present_Price  Kms_Driven  \
0       ritz  maruti suzuki  2014           3.35           5.59       27000   
1        sx4  maruti suzuki  2013           4.75           9.54       43000   
2       ciaz  maruti suzuki  2017           7.25           9.85        6900   
3    wagon r  maruti suzuki  2011           2.85           4.15        5200   
4      swift  maruti suzuki  2014           4.60           6.87       42450   
..       ...            ...   ...            ...            ...         ...   
296     city          honda  2016           9.50          11.60       33988   
297     brio          honda  2015           4.00           5.90       60000   
298     city          honda  2009           3.35          11.00       87934   
299     city          honda  2017          11.50          12.50        9000   
300     brio          honda  2016           5.30           5.90        5464   

    Fuel_Type Transmission  
0      Petrol       Manual  
1      Diesel       Manual  
2      Petrol       Manual  
3      Petrol       Manual  
4      Diesel       Manual  
..        ...          ...  
296    Diesel       Manual  
297    Petrol       Manual  
298    Petrol       Manual  
299    Diesel       Manual  
300    Petrol       Manual  

[301 rows x 8 columns]

In [ ]:
df1 = df1.drop("Present_Price",axis = 1)
df1

Car_Name        company  Year  Selling_Price  Kms_Driven Fuel_Type  \
0       ritz  maruti suzuki  2014           3.35       27000    Petrol   
1        sx4  maruti suzuki  2013           4.75       43000    Diesel   
2       ciaz  maruti suzuki  2017           7.25        6900    Petrol   
3    wagon r  maruti suzuki  2011           2.85        5200    Petrol   
4      swift  maruti suzuki  2014           4.60       42450    Diesel   
..       ...            ...   ...            ...         ...       ...   
296     city          honda  2016           9.50       33988    Diesel   
297     brio          honda  2015           4.00       60000    Petrol   
298     city          honda  2009           3.35       87934    Petrol   
299     city          honda  2017          11.50        9000    Diesel   
300     brio          honda  2016           5.30        5464    Petrol   

    Transmission  
0         Manual  
1         Manual  
2         Manual  
3         Manual  
4         Manual  
..           ...  
296       Manual  
297       Manual  
298       Manual  
299       Manual  
300       Manual  

[301 rows x 7 columns]

In [ ]:
df1.to_csv("cleaned_car_dekho")

# MODEL

In [ ]:
X = df1.drop(columns = 'Selling_Price')
X

Car_Name        company  Year  Kms_Driven Fuel_Type Transmission
0       ritz  maruti suzuki  2014       27000    Petrol       Manual
1        sx4  maruti suzuki  2013       43000    Diesel       Manual
2       ciaz  maruti suzuki  2017        6900    Petrol       Manual
3    wagon r  maruti suzuki  2011        5200    Petrol       Manual
4      swift  maruti suzuki  2014       42450    Diesel       Manual
..       ...            ...   ...         ...       ...          ...
296     city          honda  2016       33988    Diesel       Manual
297     brio          honda  2015       60000    Petrol       Manual
298     city          honda  2009       87934    Petrol       Manual
299     city          honda  2017        9000    Diesel       Manual
300     brio          honda  2016        5464    Petrol       Manual

[301 rows x 6 columns]

In [ ]:
Y = df1['Selling_Price']
Y

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...  
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [ ]:
ohe = OneHotEncoder()
ohe.fit(X[['Car_Name',"company","Fuel_Type","Transmission"]])

OneHotEncoder()

In [ ]:
column_trans = make_column_transformer((OneHotEncoder(categories = ohe.categories_),['Car_Name',"company","Fuel_Type","Transmission"]),remainder = 'passthrough')
lr = LinearRegression()

In [ ]:
pipe = make_pipeline(column_trans,lr)
pipe.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['800', 'Activa 3g', 'Activa 4g', 'Bajaj  ct 100',
       'Bajaj Avenger 150', 'Bajaj Avenger 150 street',
       'Bajaj Avenger 220', 'Bajaj Avenger 220 dtsi',
       'Bajaj Avenger Street 220', 'Bajaj Discover 100',
       'Bajaj Discover 125', 'Bajaj Dominar 400', 'Baj...
       'land cruiser', 'omni', 'ritz', 's cross', 'swift', 'sx4', 'verna',
       'vitara brezza', 'wagon r', 'xcent'], dtype=object),
                                                                            array(['bajaj', 'hero', 'honda', 'hyndai', 'maruti suzuki', 'other',
       'toyota', 'tvs', 'yamaha'], dtype=object),
                                                                            array(['CNG', 'Diesel', 'Petrol'], dtype=object),
                                                                            array(['Automatic', 'Manual'], dtype=object)]),
                                                  ['Car_Name', 'company',
                                                   'Fuel_Type',
                                                   'Transmission'])])),
                ('linearregression', LinearRegression())])

In [ ]:
Y_pred = pipe.predict(X_test)

In [ ]:
r2_score(Y_test,Y_pred)

0.8350625770547035

In [ ]:
scores = []
for i in range(1000):
  X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state = i)
  lr = LinearRegression()
  pipe = make_pipeline(column_trans,lr)
  pipe.fit(X_train,Y_train)
  Y_pred = pipe.predict(X_test)
  scores.append(r2_score(Y_test,Y_pred))


In [ ]:
np.argmax(scores)

998

In [ ]:
scores[np.argmax(scores)]

0.9089527987381915

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state =np.argmax(scores) )
lr = LinearRegression()
pipe = make_pipeline(column_trans,lr)
pipe.fit(X_train,Y_train)
Y_pred = pipe.predict(X_test)
r2_score(Y_test,Y_pred)


0.9089527987381915

In [ ]:
import pickle

In [ ]:
pickle.dump(pipe,open('LinearRegressionModel.pkl'))

In [85]:
pipe.predict(pd.DataFrame([['ritz','maruti suzuki',2014,27000,'Petrol','Manual']],columns = ['Car_Name',"company","Year","Kms_Driven","Fuel_Type","Transmission"]))

array([3.84665016])